version: '2'
services:
  dspace:
    image: dspace
    ports:
     - "8082:8080"
    volumes_from:
     - dspacestorage
    environment:
     - PGPASSWORD=postgres
    restart: always
    mem_limit: 4g
  postgres:
    image: postgres
    volumes_from:
     - postgresstorage
    environment:
     - POSTGRES_PASSWORD=postgres
    restart: always
    mem_limit: 256m
  dspacestorage:
    image: dspace
    volumes:
     - dspacehome:/opt/dspace/
     - dspacesrc:/home/dspace/
    restart: always
    mem_limit: 256m
  postgresstorage:
    image: postgres
    volumes:
     - postgresdspace:/var/lib/postgresql/data
    restart: always
    mem_limit: 256m
volumes:
  dspacehome:
  dspacesrc:
  postgresdspace:
